In [2]:
import pandas as pd
import numpy as np
from datetime import datetime as dt
from dateutil import parser
import os
from os import listdir
from os.path import isfile, join

In [3]:
os.chdir(r"C:\Users\pauli\Documents\M2\Text Mining\projet\Disney-Text-Mining\fichiers")
mypath = os.getcwd()
#os.chdir(r"C:\Users\cornuch\Desktop\SISE\Text_mining\projet_disney")

In [10]:

onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
all_data = pd.DataFrame()

for file in onlyfiles:
    current_data = pd.read_csv(file, sep=';')  
    all_data = pd.concat([all_data,current_data])
print(all_data)

df_newport=pd.read_csv('Scrapping_Newport_Bay_Club.csv',sep=';')
df_newport=pd.read_csv('Scrapping_Cheyenne.csv',sep=';')
df_newport=pd.read_csv('Scrapping_Davy_Crockett_Ranch.csv',sep=';')
df_newport=pd.read_csv('Scrapping_New_York.csv',sep=';')
df_newport=pd.read_csv('Scrapping_Santa_Fe.csv',sep=';')
df_newport=pd.read_csv('Scrapping_Sequoia_Lodge.csv',sep=';')


#et les autres ...

         Names     Country                                          room_type  \
0      Florine      France  Chambre Woody's Roundup à Proximité des Instal...
1        Andre      Brésil  Chambre Woody's Roundup à Proximité des Instal...
2     Veronica     Espagne                   Chambre Standard Woody's Roundup
3      Jessica  États-Unis  Chambre Double/Lit Gigogne Woody's Roundup - C...
4        Julie    Pays-Bas                   Chambre Standard Woody's Roundup
...        ...         ...                                                ...
1535     empty       empty                                              empty
1536     empty       empty                                              empty
1537     empty       empty                                              empty
1538     empty       empty                                              empty
1539     empty       empty                                              empty

     nuitee reservation_date traveler_infos  \
0         1    Décembre 2022         Couple
1         1    Décembre 2022        Famille
2         1    Décembre 2022        Famille
3         1    Décembre 2022        Famille
4         1    Décembre 2022        Famille
...     ...              ...            ...
1535      e            empty          empty
1536      e            empty          empty
1537      e            empty          empty
1538      e            empty          empty
1539      e            empty          empty

                                 date_review  \
0       Commentaire envoyé le 1 janvier 2023
1     Commentaire envoyé le 31 décembre 2022
2     Commentaire envoyé le 31 décembre 2022
3     Commentaire envoyé le 31 décembre 2022
4     Commentaire envoyé le 31 décembre 2022
...                                      ...
1535                                   empty
1536                                   empty
1537                                   empty
1538                                   empty
1539                                   empty

                                     review_title grade_review  \
0                                    Exceptionnel           10
1                                       Très bien            8
2                                       Très bien            8
3     Fun for the kids but overpriced and crowded            6
4                                            Mwoa            5
...                                           ...          ...
1535                                        empty        empty
1536                                        empty        empty
1537                                        empty        empty
1538                                        empty        empty
1539                                        empty        empty

     positive_review negative_review usefulness_review  \
0              empty           empty                 0
1              empty           empty                 0
2              empty           empty                 0
3                NaN             NaN                Na
4                NaN             NaN                Na
...              ...             ...               ...
1535           empty           empty                 0
1536           empty           empty                 0
1537           empty           empty                 0
1538           empty           empty                 0
1539           empty           empty                 0

                                               UniqueID          hotel
0     FlorineFranceChambre Woody's Roundup à Proximi...       Cheyenne
1     AndreBrésilChambre Woody's Roundup à Proximité...       Cheyenne
2     VeronicaEspagneChambre Standard Woody's Roundu...       Cheyenne
3     JessicaÉtats-UnisChambre Double/Lit Gigogne Wo...       Cheyenne
4     JuliePays-BasChambre Standard Woody's RoundupD...       Cheyenne
...                                                 ...            ...
1535                emptyemptyemptyemptyemptyemptyempty  Sequoia_Lodge
1536                emptyemptyemptyemptyemptyemptyempty  Sequoia_Lodge
1537                emptyemptyemptyemptyemptyemptyempty  Sequoia_Lodge
1538                emptyemptyemptyemptyemptyemptyempty  Sequoia_Lodge
1539                emptyemptyemptyemptyemptyemptyempty  Sequoia_Lodge

[11260 rows x 14 columns]

In [130]:
#fusionner tout ici ? 
df = df_newport.copy()

In [131]:
df.head()

,Names,Country,room_type,nuitee,reservation_date,traveler_infos,date_review,review_title,grade_review,positive_review,negative_review,usefulness_review,hotel
0,Ludovic,La Réunion,Chambre Supérieure - Côté Lac,2,Octobre 2022,Famille,Commentaire envoyé le 9 octobre 2022,Inoubliable,10,Le petit déjeuner et l'excellent buffet pour l...,NaN,NaN,Disney's Newport Bay Club
1,Julien,France,Chambre Supérieure,1,Décembre 2022,Couple,Commentaire envoyé le 15 décembre 2022,Très bien,"8,0","Les navettes pour accéder au parc,\r\nLa taill...",R.a.s,NaN,Disney's Newport Bay Club
2,Celine,France,Chambre Supérieure,2,Décembre 2022,Famille,Commentaire envoyé le 14 décembre 2022,Agréable,"6,0",Û,NaN,NaN,Disney's Newport Bay Club
3,Diego,France,Chambre Supérieure,1,Novembre 2022,Famille,Commentaire envoyé le 30 novembre 2022,Agréable,"6,0",la proximité du parc Disneyland Paris,"la qualité de la chambre n’était pas top, vieu...",NaN,Disney's Newport Bay Club
4,Fabienne,Belgique,Chambre Supérieure,1,Novembre 2022,Famille,Commentaire envoyé le 18 novembre 2022,déçue qualité prix,"6,0",l emplacement,la propreté,NaN,Disney's Newport Bay Club

In [132]:
df.shape

(2276, 13)

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2276 entries, 0 to 2275
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Names              2276 non-null   object
 1   Country            2274 non-null   object
 2   room_type          2130 non-null   object
 3   nuitee             2276 non-null   int64
 4   reservation_date   2276 non-null   object
 5   traveler_infos     2276 non-null   object
 6   date_review        2276 non-null   object
 7   review_title       2274 non-null   object
 8   grade_review       2276 non-null   object
 9   positive_review    627 non-null    object
 10  negative_review    494 non-null    object
 11  usefulness_review  244 non-null    object
 12  hotel              2276 non-null   object
dtypes: int64(1), object(12)
memory usage: 231.3+ KB

## Ajout dates

In [134]:
def clean_date_ajout(df):
    
    df_moisreview=df['date_review'].map(str)
    for i in range(df.shape[0]):
        df_moisreview[i]=df_moisreview[i].split()[4]
    df_moisreservation=df['reservation_date'].map(str)
    for i in range(df.shape[0]):
        df_moisreservation[i]=df_moisreservation[i].split()[0].lower()
        df_anneereservation=df['reservation_date'].map(str)
    for i in range(df.shape[0]):
        df_anneereservation[i]=df_anneereservation[i].split()[1]
        from time import strptime
    import locale
    locale.setlocale(locale.LC_TIME,'')

    list_mois_num = [strptime(moisreservation,'%B').tm_mon for moisreservation in df_moisreservation]
    list_mois_com = [strptime(moisreview,'%B').tm_mon for moisreview in df_moisreview]
    delai = [com - num if com-num>-1 else 12+(com-num) for com, num in zip(list_mois_com, list_mois_num)]

    d = {'month_str': df_moisreservation, 'month_num': list_mois_num, 'year' : df_anneereservation,  'delay_comment': delai}
    df_date = pd.DataFrame(data=d)
    df = pd.concat([df,df_date], join = 'outer', axis = 1)
    return(df)

In [135]:
def ajout_levels(df):
    conditionlist_note = [
    (df['grade_review'] >= 8) ,
    (df['grade_review'] > 5) & (df['grade_review'] <8),
    (df['grade_review'] <= 5)]
    choicelist_note = [2,1,0]
    df['level_grade_review'] = np.select(conditionlist_note, choicelist_note, default='Not Specified')
    conditionlist_hotel = [
    (df['hotel'] == "Disney's Newport Bay Club")]
    choicelist_hotel = [6]
    df['level_hotel'] = np.select(conditionlist_hotel, choicelist_hotel, default='Not Specified')
    return(df)

In [136]:
def recodage(df, var_tofloat):
    for i in var_tofloat:
        df[i] = df[i].str.replace(",",".")
        df[i] = pd.to_numeric(df[i], downcast="float")
    return(df)

In [137]:
df = recodage(df, ['grade_review'])

In [138]:
df = ajout_levels(df)

In [139]:
df = clean_date_ajout(df)

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2276 entries, 0 to 2275
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Names               2276 non-null   object
 1   Country             2274 non-null   object
 2   room_type           2130 non-null   object
 3   nuitee              2276 non-null   int64
 4   reservation_date    2276 non-null   object
 5   traveler_infos      2276 non-null   object
 6   date_review         2276 non-null   object
 7   review_title        2274 non-null   object
 8   grade_review        2276 non-null   float32
 9   positive_review     627 non-null    object
 10  negative_review     494 non-null    object
 11  usefulness_review   244 non-null    object
 12  hotel               2276 non-null   object
 13  level_grade_review  2276 non-null   object
 14  level_hotel         2276 non-null   object
 15  month_str           2276 non-null   object
 16  month_num           2276 non-null   int64
 17  year                2276 non-null   object
 18  delay_comment       2276 non-null   int64
dtypes: float32(1), int64(3), object(15)
memory usage: 329.1+ KB

In [141]:
df = df.drop_duplicates(keep='first')

In [142]:
df.drop(df[(df.delay_comment >3)].index , inplace=True)

In [143]:
df=df.reset_index(drop=True)

In [144]:
df_date=df['date_review'].map(str)

In [145]:
for i in range(df.shape[0]):
    pos=df_date[i].find('le')
    #extraction
    df_date[i] = df_date[i][pos+2:] 
df['date_review']=df_date

In [146]:
df.head()

,Names,Country,room_type,nuitee,reservation_date,traveler_infos,date_review,review_title,grade_review,positive_review,negative_review,usefulness_review,hotel,level_grade_review,level_hotel,month_str,month_num,year,delay_comment
0,Ludovic,La Réunion,Chambre Supérieure - Côté Lac,2,Octobre 2022,Famille,9 octobre 2022,Inoubliable,10.0,Le petit déjeuner et l'excellent buffet pour l...,NaN,NaN,Disney's Newport Bay Club,2,6,octobre,10,2022,0
1,Julien,France,Chambre Supérieure,1,Décembre 2022,Couple,15 décembre 2022,Très bien,8.0,"Les navettes pour accéder au parc,\r\nLa taill...",R.a.s,NaN,Disney's Newport Bay Club,2,6,décembre,12,2022,0
2,Celine,France,Chambre Supérieure,2,Décembre 2022,Famille,14 décembre 2022,Agréable,6.0,Û,NaN,NaN,Disney's Newport Bay Club,1,6,décembre,12,2022,0
3,Diego,France,Chambre Supérieure,1,Novembre 2022,Famille,30 novembre 2022,Agréable,6.0,la proximité du parc Disneyland Paris,"la qualité de la chambre n’était pas top, vieu...",NaN,Disney's Newport Bay Club,1,6,novembre,11,2022,0
4,Fabienne,Belgique,Chambre Supérieure,1,Novembre 2022,Famille,18 novembre 2022,déçue qualité prix,6.0,l emplacement,la propreté,NaN,Disney's Newport Bay Club,1,6,novembre,11,2022,0

In [147]:
def date_transform (mot):
    mot = mot.replace('janvier','january')
    mot = mot.replace('février','february')
    mot = mot.replace('mars','march')
    mot = mot.replace('avril','april')
    mot = mot.replace('mai','may')
    mot = mot.replace('juin','june')
    mot = mot.replace('juillet','july')
    mot = mot.replace('août','august')
    mot = mot.replace('septembre','september')
    mot = mot.replace('octobre','october')
    mot = mot.replace('novembre','november')
    mot = mot.replace('décembre','december')
    date=parser.parse(mot).date()
    return(date)

In [148]:
#df['date']=df['date_review'].apply(date_transform)
df["date"] = pd.to_datetime(dict(year=df.year, month=df.month_num, day=1))

In [149]:
df

,Names,Country,room_type,nuitee,reservation_date,traveler_infos,date_review,review_title,grade_review,positive_review,negative_review,usefulness_review,hotel,level_grade_review,level_hotel,month_str,month_num,year,delay_comment,date
0,Ludovic,La Réunion,Chambre Supérieure - Côté Lac,2,Octobre 2022,Famille,9 octobre 2022,Inoubliable,10.0,Le petit déjeuner et l'excellent buffet pour l...,NaN,NaN,Disney's Newport Bay Club,2,6,octobre,10,2022,0,2022-10-01
1,Julien,France,Chambre Supérieure,1,Décembre 2022,Couple,15 décembre 2022,Très bien,8.0,"Les navettes pour accéder au parc,\r\nLa taill...",R.a.s,NaN,Disney's Newport Bay Club,2,6,décembre,12,2022,0,2022-12-01
2,Celine,France,Chambre Supérieure,2,Décembre 2022,Famille,14 décembre 2022,Agréable,6.0,Û,NaN,NaN,Disney's Newport Bay Club,1,6,décembre,12,2022,0,2022-12-01
3,Diego,France,Chambre Supérieure,1,Novembre 2022,Famille,30 novembre 2022,Agréable,6.0,la proximité du parc Disneyland Paris,"la qualité de la chambre n’était pas top, vieu...",NaN,Disney's Newport Bay Club,1,6,novembre,11,2022,0,2022-11-01
4,Fabienne,Belgique,Chambre Supérieure,1,Novembre 2022,Famille,18 novembre 2022,déçue qualité prix,6.0,l emplacement,la propreté,NaN,Disney's Newport Bay Club,1,6,novembre,11,2022,0,2022-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2267,Anonyme,Brésil,NaN,2,Janvier 2020,Famille,14 janvier 2020,Exceptionnel,10.0,NaN,NaN,NaN,Disney's Newport Bay Club,2,6,janvier,1,2020,0,2020-01-01
2268,Anonyme,Royaume-Uni,NaN,2,Décembre 2019,Couple,14 janvier 2020,Fabuleux,9.2,NaN,NaN,NaN,Disney's Newport Bay Club,2,6,décembre,12,2019,1,2019-12-01
2269,Anonyme,Portugal,NaN,2,Janvier 2020,Couple,13 janvier 2020,Fabuleux,9.0,NaN,NaN,NaN,Disney's Newport Bay Club,2,6,janvier,1,2020,0,2020-01-01
2270,Anonyme,Japon,NaN,3,Janvier 2020,Famille,8 janvier 2020,Décevant,4.2,NaN,NaN,NaN,Disney's Newport Bay Club,0,6,janvier,1,2020,0,2020-01-01
2271,Anonyme,Japon,NaN,2,Décembre 2019,Groupe,30 décembre 2019,Passable,5.0,NaN,NaN,NaN,Disney's Newport Bay Club,0,6,décembre,12,2019,0,2019-12-01

In [150]:
df_clean=df.copy()

In [151]:
df_clean

,Names,Country,room_type,nuitee,reservation_date,traveler_infos,date_review,review_title,grade_review,positive_review,negative_review,usefulness_review,hotel,level_grade_review,level_hotel,month_str,month_num,year,delay_comment,date
0,Ludovic,La Réunion,Chambre Supérieure - Côté Lac,2,Octobre 2022,Famille,9 octobre 2022,Inoubliable,10.0,Le petit déjeuner et l'excellent buffet pour l...,NaN,NaN,Disney's Newport Bay Club,2,6,octobre,10,2022,0,2022-10-01
1,Julien,France,Chambre Supérieure,1,Décembre 2022,Couple,15 décembre 2022,Très bien,8.0,"Les navettes pour accéder au parc,\r\nLa taill...",R.a.s,NaN,Disney's Newport Bay Club,2,6,décembre,12,2022,0,2022-12-01
2,Celine,France,Chambre Supérieure,2,Décembre 2022,Famille,14 décembre 2022,Agréable,6.0,Û,NaN,NaN,Disney's Newport Bay Club,1,6,décembre,12,2022,0,2022-12-01
3,Diego,France,Chambre Supérieure,1,Novembre 2022,Famille,30 novembre 2022,Agréable,6.0,la proximité du parc Disneyland Paris,"la qualité de la chambre n’était pas top, vieu...",NaN,Disney's Newport Bay Club,1,6,novembre,11,2022,0,2022-11-01
4,Fabienne,Belgique,Chambre Supérieure,1,Novembre 2022,Famille,18 novembre 2022,déçue qualité prix,6.0,l emplacement,la propreté,NaN,Disney's Newport Bay Club,1,6,novembre,11,2022,0,2022-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2267,Anonyme,Brésil,NaN,2,Janvier 2020,Famille,14 janvier 2020,Exceptionnel,10.0,NaN,NaN,NaN,Disney's Newport Bay Club,2,6,janvier,1,2020,0,2020-01-01
2268,Anonyme,Royaume-Uni,NaN,2,Décembre 2019,Couple,14 janvier 2020,Fabuleux,9.2,NaN,NaN,NaN,Disney's Newport Bay Club,2,6,décembre,12,2019,1,2019-12-01
2269,Anonyme,Portugal,NaN,2,Janvier 2020,Couple,13 janvier 2020,Fabuleux,9.0,NaN,NaN,NaN,Disney's Newport Bay Club,2,6,janvier,1,2020,0,2020-01-01
2270,Anonyme,Japon,NaN,3,Janvier 2020,Famille,8 janvier 2020,Décevant,4.2,NaN,NaN,NaN,Disney's Newport Bay Club,0,6,janvier,1,2020,0,2020-01-01
2271,Anonyme,Japon,NaN,2,Décembre 2019,Groupe,30 décembre 2019,Passable,5.0,NaN,NaN,NaN,Disney's Newport Bay Club,0,6,décembre,12,2019,0,2019-12-01

In [153]:
df_clean.to_csv("C:/Users/pauli/Documents/M2/Text Mining/projet/Disney-Text-Mining/fichiers/df_clean.csv",sep=';', index=False, encoding="utf-8-sig")